-- 코드를 작성해주세요
SELECT E3.ID
  FROM ECOLI_DATA AS E1
  LEFT JOIN ECOLI_DATA AS E2 ON E2.PARENT_ID = E1.ID
  LEFT JOIN ECOLI_DATA AS E3 ON E3.PARENT_ID = E2.ID
  # LEFT JOIN ECOLI_DATA AS E4 ON E4.PARENT_ID = E3.ID
  WHERE E1.PARENT_ID IS NULL AND E3.ID IS NOT NULL
 ORDER BY E3.ID;